name: Open State CI/CD

on:
  release:
    types: [published]

env:
  IMAGE_TAG: latest

jobs:

  build:
    name: Build project
    runs-on: ubuntu-latest
    continue-on-error: false
    if: github.event.action == 'published'

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare Java SDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build project
        run: ./gradlew assemble

      - name: Save executables
        uses: actions/upload-artifact@v2
        with:
          name: assembles_${{ github.sha }}
          path: build/libs/*.jar

  deploy-production:
    name: Deploy Production
    runs-on: ubuntu-latest
    continue-on-error: false
    needs: [build]

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy server
        run: |
          sudo apt install openssh-client
          sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          eval $(ssh-agent -s)
          echo "${{ secrets.PROD_DEPLOY_SSH_KEY }}" | tr -d '\r' | ssh-add - > /dev/null
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan ${{ secrets.PROD_SERVER }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          export DOCKER_HOST="ssh://gitlab@${{ secrets.PROD_SERVER }}"
          export BITCOIN_NODE="${{ secrets.PROD_BITCOIN_NODE }}"
          export BITCOIN_USERNAME="${{ secrets.PROD_BITCOIN_USERNAME }}"
          export BITCOIN_PASSWORD="${{ secrets.PROD_BITCOIN_PASSWORD }}"
          export ETHEREUM_NODE_ADDRESS="${{ secrets.PROD_ETHEREUM_NODE_ADDRESS }}"
          export MONGODB_PASSWORD="${{ secrets.PROD_MONGO_PASSWORD }}"
          export DOCKER_IMAGE_TAG="openplatform/open-state:${{ env.IMAGE_TAG }}"
          docker login -u ${{ secrets.DOCKERHUB_USER_NAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

          sudo docker-compose -f docker-compose.yml up -d -e "MONGODB_PASSWORD=${{ secrets.PROD_MONGO_PASSWORD }}" \
          -e "DOCKER_IMAGE_TAG=openplatform/open-state:${{ env.IMAGE_TAG }} \

          sudo docker pull openplatform/open-state:${{ env.IMAGE_TAG }}
          sudo docker run -d --name 'openplatform/open-state' --restart=always \
                                               -p 8080:8080 \
                                               -e "BITCOIN_NODE=${{ secrets.PROD_BITCOIN_NODE }}" \
                                               -e "BITCOIN_USERNAME=${{ secrets.PROD_BITCOIN_USERNAME }}" \
                                               -e "BITCOIN_PASSWORD=${{ secrets.PROD_BITCOIN_PASSWORD }}" \
                                               -e "ETHEREUM_NODE_ADDRESS=${{ secrets.PROD_ETHEREUM_NODE_ADDRESS }}" \
                                               -e "MONGODB_PASSWORD=${{ secrets.PROD_MONGO_PASSWORD }}" \
                                               openplatform/open-state:${{ env.IMAGE_TAG }}
